version: "3"
services:

  nginx:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    depends_on:
      - client
    ports:
      - 80:80

  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    volumes:
    - /app/node_modules
    - ./client:/app

  server:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
      # ports:
        # - 8000:8000
    volumes:
      - ./server:/app
    depends_on:
      - postgres
    environment:
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
      - PGPORT=5432

  postgres:
    image: postgres:latest
    ports:
      - 5432:5432
